version: '3'

services: 
  nginx:
    build: docker/nginx

    volumes:
      - ./:/var/www/html

    networks:
      - web
    ports:
      - "80:80"
    expose:
      - 80
    

networks:
  web:
    driver: bridge

